### ISSUE TITLE
Publish gem update

### ISSUE THREAD

**Issue by jeduden** [bitbar/testdroid-api-client-ruby#18]
Hoi !

could you publish the latest changes to a new version of the gem ?

Thanks !

**Comment by srautiai** [comment]
Version 0.3.0 is out: https://rubygems.org/gems/testdroid-api-client/versions/0.3.0

**Comment by jeduden** [comment]
@srautiai  version 0.3.0 is from December 19, 2014.

The latest changes in master are from today. ;)

It would be great if you can publish these, since I would like to use ApiKey support.
